# Global config
# Variables can be accessed via site.variable_name

name: Humane Software Development
copyright_name: Dmitrii Abramov
title: Dmitrii Abramov — Humane Software Development
email: dmitrii.abramov@outlook.com
description: >- # this means to ignore newlines until "baseurl:"
  The blog about Software Development and about people in Software Development.
baseurl: 'https://karvozavr.github.io' # the subpath of your site, e.g. /blog
url: 'https://karvozavr.github.io' # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: karvozavr
github_username:  karvozavr
google_analytics: 'UA-186441238-1'
disqus: 'dmitrii-abramov'
logo: 'assets/images/logo.png'
include: ["_pages"]
permalink: /:title/

# Build settings
markdown: kramdown
remote_theme: karvozavr/mediumish-theme-jekyll
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives

authors:
  dmitrii-abramov:
    name: Dmitrii Abramov
    display_name: Dmitrii Abramov
    avatar: assets/images/homepage/photo.png
    email: dmitrii.abramov@outlook.com
    web: https://karvozavr.github.io
    twitter: https://twitter.com/karvozavr
    description: "Passionate Software Developer"

# pagination
paginate: 6
paginate_path: /page:num/

adsense: "disabled"

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - changelog.md
  - LICENSE.txt
  - README.md
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
